### ISSUE TITLE
Duckling

### ISSUE THREAD

**Issue by eutampieri** [rodolf0/tox#1]
I was planning to port facebook/duckling too. Do you want some help?

**Comment by rodolf0** [comment]
Sure thing! I don't have any roadmap for this though. I wouldn't call this a duckling port at all... mostly inspired on it to satisfy my curiosity around time evaluation and parsers.

One way to expand the project is to figure a way to fuzzy evaluate an expression out of a non exact match or in other words extract the relevant "time" bit out of a paragraph / sentence.
