### ISSUE TITLE
Serde deserialize (and maybe serialize) implementation for shunting?

### ISSUE THREAD

**Issue by TheLostLambda** [rodolf0/tox#4]
Hey! This looks like a super cool collection of libraries and is just what I need for parsing some math expressions.

I think I could probably write some Serde implementations at some point and just was wondering if that's in-scope for this library. If so, I can hopefully open a PR for it sometime!

**Comment by rodolf0** [comment]
hey @TheLostLambda glad you like it :D since these are mostly for learning I'd like to keep dependencies to a minimum. Maybe implement them as different crates?

**Comment by TheLostLambda** [comment]
No worries! That makes sense to me! I eventually ended up not needing those implementations, but I might consider a tiny Crate with a newtype wrapper and these implementations. Thanks for merging the `Clone` and `Debug` derives though! Now I can move back to upstream :)
