### ISSUE TITLE
example does work as is

### ISSUE THREAD

**Issue by sbeckeriv** [rodolf0/tox#6]
Dearest maintainer,

I found a few problems with copying the example. The first was the arg reading told me the input didnt live long enough. I fought with it for a while and lost. I hard coded my example in to a string. The second is it would be nice to see lexers. I know its in the cargo file. maybe adding `extern crate lexers;`?

I am running rustc 1.47.0-nightly (6c8927b0c 2020-07-26) 2018 edition. 

Thanks!
Becker

**Comment by rodolf0** [comment]
Hey @sbeckeriv can you point at the specific example so I can test it?

**Comment by sbeckeriv** [comment]
@rodolf0 very sorry. I see there are many trees to the repo now. https://github.com/rodolf0/tox/blob/master/abackus/examples/ebnftree.rs#L29 This was the example I was trying to run. Turns out I was not dealing with a real EBNF file so I did not move forward with abackus.

Thanks for looking.
Becker

**Comment by rodolf0** [comment]
Built and ran the mentioned example and works, I'll close this for now.

**Comment by sbeckeriv** [comment]
Very sorry to waste your time. I should have created an example repro problem first. i dont know what i did wrong before.
